language: java
sudo: required
dist: precise
group: edge
jdk: oraclejdk9

script:
  - set -o pipefail
  - "mvn clean checkstyle:checkstyle findbugs:findbugs install -Dmaven.compiler.source=1.6 -Dmaven.compiler.target=1.6 | egrep -v 'Download(ing|ed): '"
  - cd benchmark
  - "mvn clean package | egrep -v 'Download(ing|ed): '"

after_success:
  - bash <(curl -s https://codecov.io/bash)
